version: "3"
services:
    provider:
        build: .
        ports: 
            - "3000:3000"
        volumes: 
            - .:/pact/provider
        environment: 
            FLASK_ENV: development